name: CI

on:
  pull_request:
    branches: [ master ]
    paths:
      - "src/**"
      - "tests/**"
      - ".github/workflows/CI.yml"
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04

    env:
      OPENCV_VERSION: 4.10.0

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache OpenCV
        id: opencv-cache
        uses: actions/cache@v4
        with:
          path: /tmp/opencv-install
          key: ${{ runner.os }}-${{ env.OPENCV_VERSION }}

      - name: Build OpenCV
        if: steps.opencv-cache.outputs.cache-hit != 'true'
        run: |
          cp ./.devcontainer/install-opencv.sh /tmp/
          chmod +x /tmp/install-opencv.sh
          cd /tmp
          ./install-opencv.sh $OPENCV_VERSION /tmp/opencv-install

      - name: Restore OpenCV
        run: sudo cp -r /tmp/opencv-install /usr/local

      - name: Build
        run: |
          cmake -S . -B build -DTLCT_BUILD_TESTS=ON
          cmake --build build --parallel

      - name: Run tests
        run: |
          cd build
          ctest
