name: CI

on:
  schedule:
    - cron: "42 6 * * *"
  pull_request:
    branches: [ master ]
    paths:
      - "src/**"
      - "tests/**"
      - ".github/workflows/CI.yml"
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache OpenCV
        id: cache-ocv
        uses: actions/cache@v4
        with:
          path: |
            /usr/local/lib/libopencv*
            /usr/local/include/opencv4/*
            /usr/local/lib/cmake/opencv4/*
          key: ${{ hashFiles('.devcontainer/Dockerfile') }}

      - name: Install OpenCV
        if: steps.cache-ocv.outputs.cache-hit != 'true'
        run: |
          chmod +x .devcontainer/install-opencv.sh
          .devcontainer/install-opencv.sh

      - name: Build
        run: |
          cmake -S . -B build -DTLCT_BUILD_TESTS=ON
          cd build
          cmake --build . --config Debug --parallel

      - name: Run tests
        run: ctest
